/* ============================================================================
   Santa Natura — Listado oficial de productos y precios (Enero 2026)
   ----------------------------------------------------------------------------
   FUENTE ÚNICA DE VERDAD. Para actualizar precios, edita SOLO este archivo.

   Campos:
     id          Identificador único (no reutilizar ids de productos retirados).
     categoria   Línea de la lista oficial de precios: "Línea General" |
                 "Línea Convencional" | "Línea Consumo Saludable" | "Packs".
                 Ya NO se muestra en la web; decide qué escala de descuentos por
                 cantidad aplica (20/25/30/40% o 15%).
     categorias  Categorías reales de santanatura.com.pe. Son las que se ven y
                 por las que se navega. Un producto está en VARIAS a la vez.
                 Los nombres válidos son los de COLECCIONES, al final del archivo.
     producto    Nombre visible en el catálogo.
     puntos      Puntos que otorga el producto. Se acumulan en el resumen del pedido.
     pvp         Precio de Venta al Público VIGENTE: el que se cobra, el que suma
                 en el carrito y el que viaja en el mensaje de WhatsApp. Si el
                 producto está en oferta, aquí va el precio rebajado y el de lista
                 se guarda en precio_original.
     descuentos  Precios especiales por cantidad, por % de descuento.
                 NO se muestran en la web (son precios de negociación). Se usan
                 internamente al cerrar el pedido por WhatsApp.

   Campos opcionales que puedes agregar a cualquier producto:
     imagen             Ruta o URL de la foto. Si falta, se dibuja un placeholder
                        de marca. Para usar una foto propia, déjala dentro de la
                        carpeta img/ y escribe aquí "img/nombre-del-archivo.jpg".
                        OJO: respeta mayúsculas y minúsculas del nombre real.
     descripcion        Texto corto que se ve en la ficha del producto.
     precio_original    Precio de lista, se dibuja tachado al lado del pvp.
                        Solo para productos y packs con oferta pública vigente
                        en santanatura.com.pe.
     etiqueta_descuento Globo rojo de la tarjeta, p. ej. "-25%". Debe cuadrar con
                        el redondeo de pvp contra precio_original.

   Ejemplo:
     {"id": 1, ..., "imagen": "img/allin-surka.jpg", "descripcion": "Texto..."}
   ========================================================================== */

const PRODUCTS = [
  {"id": 1, "categoria": "Línea General", "producto": "Allín surka x 200 g", "puntos": 8.33, "pvp": 42.50, "precio_original": 50.00, "etiqueta_descuento": "-15%", "imagen": "img/allin-surka-8-300x300.jpg", "descripcion": "Uso tradicional: súper jarabe natural que protege y fortalece el sistema respiratorio. Allin Surka significa «pulmones sanos».", "categorias": ["Jarabes de Miel","Jarabes naturales","Para los Pulmones"], "descuentos": {"20": 40.00, "25": 37.50, "30": 35.00, "40": 30.00}},
  {"id": 2, "categoria": "Línea General", "producto": "Bebida Dipluss x 500 ml", "puntos": 11.33, "pvp": 68.00, "imagen": "img/bebida_dipluss-300x300.jpg", "categorias": ["Bebidas","Bebidas y concentrados","Para el Estomágo"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 3, "categoria": "Línea General", "producto": "Caja de sachet 15u batido años dorados x 10 g c/u", "puntos": 14.67, "pvp": 70.40, "precio_original": 88.00, "etiqueta_descuento": "-20%", "imagen": "img/aNos-dorados-300x300.jpg", "descripcion": "Batido Años Dorados con Tarwi, el grano andino de alto valor nutricional. Caja de 15 sachets (150 g).", "categorias": ["Batidos","Para las Defensas","Refuerzos"], "descuentos": {"20": 70.40, "25": 66.00, "30": 61.60, "40": 52.80}},
  {"id": 4, "categoria": "Línea General", "producto": "Caja de sachet 15u batido supertrim x 10 g c/u", "puntos": 16.50, "pvp": 99.00, "imagen": "img/supertrim-foto-producto-300x300.jpg", "descripcion": "Supertrim: tu aliado natural para depurar el organismo y sentirte liviano. Caja de 15 sachets (150 g).", "categorias": ["Batidos","Detox","Para el Estomágo","Peso / Grasa"], "descuentos": {"20": 79.20, "25": 74.25, "30": 69.30, "40": 59.40}},
  {"id": 5, "categoria": "Línea General", "producto": "Caja de sachet 15u batido yo vital hombre x 10 g c/u", "puntos": 14.67, "pvp": 88.00, "imagen": "img/yo-vital-hombre-7-300x300.jpg", "descripcion": "Batido Yo Vital Hombre: superalimento natural que fortalece el cuerpo del hombre. Caja de 15 sachets (150 g).", "categorias": ["Batidos","Favoritos de los hombres","Para las Defensas","Refuerzos"], "descuentos": {"20": 70.40, "25": 66.00, "30": 61.60, "40": 52.80}},
  {"id": 6, "categoria": "Línea General", "producto": "Caja de sachet 15u batido yo vital mujer x 10 g c/u", "puntos": 14.67, "pvp": 88.00, "imagen": "img/yo-vital-mujer-1-800x800.jpg", "descripcion": "Batido Yo Vital Mujer: mezcla de superalimentos pensada para la mujer. Caja de 15 sachets (150 g).", "categorias": ["Batidos","Favoritos de las mujeres","Para las Defensas","Refuerzos","Top Ventas"], "descuentos": {"20": 70.40, "25": 66.00, "30": 61.60, "40": 52.80}},
  {"id": 7, "categoria": "Línea General", "producto": "Caja de sachet 15u batido yo vital niños x 10 g c/u", "puntos": 14.67, "pvp": 70.40, "precio_original": 88.00, "etiqueta_descuento": "-20%", "imagen": "img/yo-vital-ninos-300x300.jpg", "descripcion": "Mezcla de superalimentos naturales de los Andes y la Amazonía, en presentación para niños. Caja de 15 sachets (150 g).", "categorias": ["Batidos","Para las Defensas","Refuerzos"], "descuentos": {"20": 70.40, "25": 66.00, "30": 61.60, "40": 52.80}},
  {"id": 8, "categoria": "Línea General", "producto": "Caja de sachet 15u moringa con proteínas vegetales x 5 g c/u", "puntos": 14.67, "pvp": 88.00, "imagen": "img/110243_1-300x300.jpg", "descripcion": "La moringa, conocida popularmente como el «árbol de la vida», combinada con proteínas vegetales. Caja de 15 sachets (75 g).", "categorias": ["Batidos","Harinas del mar y tierra","Para el Estomágo","Para las Defensas","Para las Vías Urinarias","Refuerzos"], "descuentos": {"20": 70.40, "25": 66.00, "30": 61.60, "40": 52.80}},
  {"id": 9, "categoria": "Línea General", "producto": "Caja de sachet 15u tocosh con uña de gato y muña x 5 g c/u", "puntos": 14.67, "pvp": 74.80, "precio_original": 88.00, "etiqueta_descuento": "-15%", "imagen": "img/ChatGPT-Image-6-jul-2026-13_28_45-300x300.png", "descripcion": "Superalimento Tocosh con uña de gato y muña. Fórmula potenciada, caja de 15 sachets (75 g).", "categorias": ["Batidos","Detox","Harinas del mar y tierra","Para el Estomágo"], "descuentos": {"20": 70.40, "25": 66.00, "30": 61.60, "40": 52.80}},
  {"id": 10, "categoria": "Línea General", "producto": "Caja de sachet 15u toxizero x 5 g c/u", "puntos": 14.67, "pvp": 70.40, "precio_original": 88.00, "etiqueta_descuento": "-20%", "imagen": "img/toxizero-3-800x800.jpg", "descripcion": "Uso tradicional: combate el estreñimiento, limpia el colon y desintoxica las vías digestivas. Caja de 15 sachets (75 g).", "categorias": ["Batidos","Detox","Para el Estomágo"], "descuentos": {"20": 70.40, "25": 66.00, "30": 61.60, "40": 52.80}},
  {"id": 11, "categoria": "Línea General", "producto": "Cartimix x 100 g", "puntos": 11.66, "pvp": 70.00, "imagen": "img/cartimix-3-300x300.jpg", "categorias": ["Favoritos de los hombres","Harinas del mar y tierra","Para los Huesos","Refuerzos","Top Ventas"], "descuentos": {"20": 56.00, "25": 52.50, "30": 49.00, "40": 42.00}},
  {"id": 12, "categoria": "Línea General", "producto": "Cartimix x 200 g", "puntos": 19.17, "pvp": 86.25, "precio_original": 115.00, "etiqueta_descuento": "-25%", "imagen": "img/cartimix-3-300x300.jpg", "categorias": ["Favoritos de los hombres","Harinas del mar y tierra","Para los Huesos","Refuerzos","Top Ventas"], "descuentos": {"20": 92.00, "25": 86.25, "30": 80.50, "40": 69.00}},
  {"id": 13, "categoria": "Línea General", "producto": "Colágeno hidrolizado maracuyá y camu camu x 450 g", "puntos": 30.00, "pvp": 135.00, "precio_original": 180.00, "etiqueta_descuento": "-25%", "imagen": "img/productossn-3-300x300.jpg", "descripcion": "Colágeno hidrolizado con maracuyá y camu camu, alimentos ricos en vitamina C. Sin saborizantes, 450 g.", "categorias": ["Colágenos","Para las Defensas","Para los Huesos"], "descuentos": {"20": 144.00, "25": 135.00, "30": 126.00, "40": 108.00}},
  {"id": 14, "categoria": "Línea General", "producto": "Colágeno hidrolizado plus x 450 g", "puntos": 30.00, "pvp": 153.00, "precio_original": 180.00, "etiqueta_descuento": "-15%", "imagen": "img/productossn-1-800x800.jpg", "descripcion": "Composición: colágeno hidrolizado, maíz morado, fresa y camu camu. Presentación de 450 g.", "categorias": ["Colágenos","Para los Huesos","Top Ventas"], "descuentos": {"20": 144.00, "25": 135.00, "30": 126.00, "40": 108.00}},
  {"id": 15, "categoria": "Línea General", "producto": "Colágeno premium x 450 g", "puntos": 30.00, "pvp": 153.00, "precio_original": 180.00, "etiqueta_descuento": "-15%", "imagen": "img/productossn-2-300x300.jpg", "descripcion": "Composición: colágeno hidrolizado y camu camu. Presentación de 450 g.", "categorias": ["Colágenos","Para los Huesos"], "descuentos": {"20": 144.00, "25": 135.00, "30": 126.00, "40": 108.00}},
  {"id": 16, "categoria": "Línea General", "producto": "Concentrado de alcachofa x 500 ml", "puntos": 11.33, "pvp": 57.80, "precio_original": 68.00, "etiqueta_descuento": "-15%", "imagen": "img/alcachofa-2-300x300.jpg", "descripcion": "Superalimento ideal e indispensable para la salud digestiva. Presentación de 500 ml.", "categorias": ["Bebidas y concentrados","Concentrados","Para el Estomágo","Para las Defensas","Para las Vías Urinarias"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 17, "categoria": "Línea General", "producto": "Concentrado de café verde y té verde x 500 ml", "puntos": 12.83, "pvp": 77.00, "imagen": "img/cafe-verde-1-300x300.jpg", "descripcion": "Mezcla de superalimentos que, según el uso tradicional, contribuyen con la pérdida de peso de manera natural.", "categorias": ["Bebidas","Bebidas y concentrados","Para el Estomágo"], "descuentos": {"20": 61.60, "25": 57.75, "30": 53.90, "40": 46.20}},
  {"id": 18, "categoria": "Línea General", "producto": "Concentrado de hojas de olivo x 500 ml", "puntos": 11.33, "pvp": 68.00, "imagen": "img/hojas-de-olivo-300x300.jpg", "descripcion": "Ideal para acompañar el control de la presión arterial. Presentación de 500 ml.", "categorias": ["Bebidas","Bebidas y concentrados","Para el Estomágo","Para las Defensas","Top Ventas"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 19, "categoria": "Línea General", "producto": "Concentrado de penca de tuna x 500 ml", "puntos": 11.33, "pvp": 54.40, "precio_original": 68.00, "etiqueta_descuento": "-20%", "imagen": "img/penca-de-tuna-2-300x300.jpg", "descripcion": "Las culturas preincas, inca, azteca y maya conocieron el gran valor nutritivo de la penca de tuna.", "categorias": ["Bebidas y concentrados","Concentrados","Para el Estomágo","Para las Defensas","Para las Vías Urinarias","Refuerzos"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 20, "categoria": "Línea General", "producto": "Concentrado de aloe vera (Sábila) x 500 ml", "puntos": 11.33, "pvp": 68.00, "imagen": "img/aloe-vera-3-800x800.jpg", "descripcion": "El aloe vera o sábila es utilizado por la medicina tradicional desde hace miles de años. Presentación de 500 ml.", "categorias": ["Bebidas","Bebidas y concentrados","Para el Estomágo","Top Ventas"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 21, "categoria": "Línea General", "producto": "Concentrado de salvia, romero y toronjil x 500 ml", "puntos": 11.33, "pvp": 68.00, "imagen": "img/salvia-toronjil-300x300.jpg", "descripcion": "Combinación de salvia, toronjil y romero, tradicionalmente usada como acompañante en momentos de estrés.", "categorias": ["Bebidas y concentrados","Concentrados","Descanso y relax","Favoritos de las mujeres","Para el Sistema Nervioso"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 22, "categoria": "Línea General", "producto": "Concentrado de té verde x 200 ml", "puntos": 5.83, "pvp": 29.75, "precio_original": 35.00, "etiqueta_descuento": "-15%", "imagen": "img/te-verde-1-300x300.jpg", "descripcion": "Té verde concentrado, uno de los antioxidantes más valorados de forma tradicional. Presentación de 200 ml.", "categorias": ["Bebidas y concentrados","Concentrados","Detox","Para el Estomágo"], "descuentos": {"20": 28.00, "25": 26.25, "30": 24.50, "40": 21.00}},
  {"id": 23, "categoria": "Línea General", "producto": "Concentrado de uña de gato x 500 ml", "puntos": 11.33, "pvp": 68.00, "imagen": "img/una-de-gato-1-800x800.jpg", "descripcion": "La poderosa uña de gato es tradicionalmente usada para potenciar el sistema de defensas.", "categorias": ["Bebidas","Bebidas y concentrados","Para las Defensas","Para los Huesos"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 24, "categoria": "Línea General", "producto": "Concentrado glucontrol x 500 ml", "puntos": 11.33, "pvp": 68.00, "imagen": "img/glucontrol-4-300x300.jpg", "descripcion": "Glucontrol es el aliado que necesitas para acompañar el control de tus niveles de glucosa. Composición: yacón, canela, pasuchaca y clavo de olor.", "categorias": ["Bebidas y concentrados","Concentrados","Para el Estomágo","Para las Defensas","Para las Vías Urinarias"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 25, "categoria": "Línea General", "producto": "Concentrado kalmapross x 500 ml", "puntos": 11.33, "pvp": 68.00, "imagen": "img/kalmapross-3-800x800.jpg", "descripcion": "Bebida Kalmapross: contiene las plantas medicinales tradicionalmente usadas para acompañar la salud de la próstata.", "categorias": ["Bebidas","Bebidas y concentrados","Favoritos de los hombres","Para las Vías Urinarias"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 26, "categoria": "Línea General", "producto": "Concentrado matico x 500 ml", "puntos": 12.50, "pvp": 75.00, "imagen": "img/matico-2-300x300.jpg", "categorias": ["Bebidas","Bebidas y concentrados","Para los Pulmones"], "descuentos": {"20": 60.00, "25": 56.25, "30": 52.50, "40": 45.00}},
  {"id": 27, "categoria": "Línea General", "producto": "Huanarpo Macho x 200 ml", "puntos": 11.33, "pvp": 68.00, "imagen": "img/huanarpo-macho-2-300x300.jpg", "descripcion": "Planta ancestral peruana con increíbles propiedades, tradicionalmente usada para favorecer la vitalidad masculina.", "categorias": ["Bebidas y concentrados","Concentrados","Favoritos de los hombres","Para las Vías Urinarias"], "descuentos": {"20": 54.40, "25": 51.00, "30": 47.60, "40": 40.80}},
  {"id": 28, "categoria": "Línea General", "producto": "Maca gelatinizada x 200 g", "puntos": 11.67, "pvp": 70.00, "imagen": "img/harina_de_maca-300x300.jpg", "descripcion": "Harina gelatinizada de maca: superalimento andino valorado mundialmente por su alcance nutricional.", "categorias": ["Favoritos de los hombres","Harinas del mar y tierra","Para el Estomágo","Para las Defensas","Refuerzos","Top Ventas"], "descuentos": {"20": 56.00, "25": 52.50, "30": 49.00, "40": 42.00}},
  {"id": 29, "categoria": "Línea General", "producto": "Miel de abejas, cebolla, rabanito y ajos x 200 ml", "puntos": 8.33, "pvp": 40.00, "precio_original": 50.00, "etiqueta_descuento": "-20%", "imagen": "img/miel-rabanitos-300x300.jpg", "descripcion": "Jarabe tradicional que une miel de abejas, cebolla, rabanito y ajos, superalimentos que se potencian entre sí.", "categorias": ["Jarabes de Miel","Jarabes naturales","Para los Pulmones"], "descuentos": {"20": 40.00, "25": 37.50, "30": 35.00, "40": 30.00}},
  {"id": 30, "categoria": "Línea General", "producto": "Plátano con miel de abejas x 200 g", "puntos": 8.33, "pvp": 42.50, "precio_original": 50.00, "etiqueta_descuento": "-15%", "imagen": "img/resina-platano-300x300.jpg", "descripcion": "La medicina tradicional usa la savia o resina del plátano como defensa natural del organismo. Con miel de abejas.", "categorias": ["Jarabes de Miel","Jarabes naturales","Para las Defensas","Para los Pulmones"], "descuentos": {"20": 40.00, "25": 37.50, "30": 35.00, "40": 30.00}},
  {"id": 31, "categoria": "Línea General", "producto": "Propóleos con copaiba y camu camu x 30 ml", "puntos": 11.67, "pvp": 52.50, "precio_original": 70.00, "etiqueta_descuento": "-25%", "imagen": "img/prop.png", "descripcion": "Propóleos concentrados mezclados con copaiba, resina obtenida del árbol copaifera de la Amazonía peruana, y camu camu.", "categorias": ["Para los Pulmones","Propóleos","Top Ventas"], "descuentos": {"20": 56.00, "25": 52.50, "30": 49.00, "40": 42.00}},
  {"id": 32, "categoria": "Línea General", "producto": "Sangre de drago x 30 ml", "puntos": 6.17, "pvp": 37.00, "imagen": "img/sangre-drago-300x300.jpg", "descripcion": "La sangre de drago es la savia roja o látex del árbol Croton, de uso tradicional amazónico. Presentación de 30 ml.", "categorias": ["Aceites"], "descuentos": {"20": 29.60, "25": 27.75, "30": 25.90, "40": 22.20}},
  {"id": 33, "categoria": "Línea General", "producto": "Súper concentrado guanábana, noni, uña de gato x 500 ml", "puntos": 12.83, "pvp": 77.00, "imagen": "img/super-concentrado-1-300x300.jpg", "descripcion": "Súper Concentrado de Guanábana, Noni y Uña de Gato: refuerza tus defensas de forma natural. Presentación de 500 ml.", "categorias": ["Bebidas y concentrados","Concentrados","Favoritos de los hombres","Para el Sistema Nervioso","Para las Defensas","Refuerzos"], "descuentos": {"20": 61.60, "25": 57.75, "30": 53.90, "40": 46.20}},
  {"id": 34, "categoria": "Línea General", "producto": "Chancapiedra x 500 ml", "puntos": 12.83, "pvp": 61.60, "precio_original": 77.00, "etiqueta_descuento": "-20%", "imagen": "img/chancapiedra-800x800.jpg", "descripcion": "Uso tradicional: indispensable para prevenir cálculos en los riñones y en la vesícula. Presentación de 500 ml.", "categorias": ["Bebidas","Bebidas y concentrados","Detox","Para las Vías Urinarias"], "descuentos": {"20": 61.60, "25": 57.75, "30": 53.90, "40": 46.20}},
  {"id": 35, "categoria": "Línea General", "producto": "Vitamagne x 200 g", "puntos": 16.50, "pvp": 74.25, "precio_original": 99.00, "etiqueta_descuento": "-25%", "imagen": "img/vitamagne-santa-natura-800x800.jpg", "categorias": ["Descanso y relax","Harinas del mar y tierra","Para el Sistema Nervioso","Para los Huesos","Refuerzos"], "descuentos": {"20": 79.20, "25": 74.25, "30": 69.30, "40": 59.40}},
  {"id": 86, "categoria": "Línea General", "producto": "ReZZZet", "puntos": 16.50, "pvp": 84.15, "precio_original": 99.00, "etiqueta_descuento": "-15%", "imagen": "img/rezzzet-frontal-1-800x800.jpg", "descripcion": "Bebida en polvo con magnesio, manzanilla y toronjil peruano, más yacón y camu camu. Triple acción: relaja el cuerpo, calma la mente y acompaña el descanso. Sabor naranja con notas de manzanilla. Una cucharada en agua tibia, 30 a 60 minutos antes de dormir.", "categorias": ["Batidos","Bebidas","Descanso y relax","Para el Sistema Nervioso","Refuerzos","Top Ventas"], "descuentos": {"20": 79.20, "25": 74.25, "30": 69.30, "40": 59.40}},
  {"id": 87, "categoria": "Línea General", "producto": "EnfoK+", "puntos": 16.50, "pvp": 84.15, "precio_original": 99.00, "etiqueta_descuento": "-15%", "imagen": "img/enfok-frontal-1-800x800.jpg", "descripcion": "Mezcla en polvo con triple maca peruana, melena de león, cacao peruano y sacha inchi amazónico: cuatro superalimentos que acompañan la energía cerebral, la concentración y la claridad mental. Sabor chocolate con maca.", "categorias": ["Batidos","Refuerzos","Top Ventas"], "descuentos": {"20": 79.20, "25": 74.25, "30": 69.30, "40": 59.40}},
  {"id": 36, "categoria": "Línea Convencional", "producto": "Aceite de copaiba x 30 ml", "puntos": 5.83, "pvp": 35.00, "imagen": "img/aceite-copaiba-300x300.jpg", "descripcion": "Oleorresina amazónica ancestral, extraída del árbol copaifera. Presentación de 30 ml.", "categorias": ["Aceites","Descanso y relax","Para las Defensas"], "descuentos": {"20": 28.00, "25": 26.25, "30": 24.50, "40": 21.00}},
  {"id": 37, "categoria": "Línea Convencional", "producto": "Algarrobina con colágeno x 370 g", "puntos": 8.33, "pvp": 50.00, "imagen": "img/algarrobina_colageno-300x300.jpg", "descripcion": "Desde tiempos ancestrales los habitantes del antiguo Perú conocieron las bondades de la algarrobina. Ahora con colágeno.", "categorias": ["Algarrobina","Cocina Natural","Para los Huesos","Top Ventas"], "descuentos": {"20": 40.00, "25": 37.50, "30": 35.00, "40": 30.00}},
  {"id": 38, "categoria": "Línea Convencional", "producto": "Miel abejas con propóleos x 200 g", "puntos": 10.00, "pvp": 48.00, "precio_original": 60.00, "etiqueta_descuento": "-20%", "imagen": "img/miel-propoleos-1-800x800.jpg", "descripcion": "Miel de abejas combinada con propóleos, la resina que las abejas recolectan de la corteza de los árboles.", "categorias": ["Jarabes de Miel","Para los Pulmones"], "descuentos": {"20": 48.00, "25": 45.00, "30": 42.00, "40": 36.00}},
  {"id": 39, "categoria": "Línea Convencional", "producto": "Miel de abejas, leche de oje, propóleos, hierba buena y paico x 200 g", "puntos": 10.00, "pvp": 60.00, "categorias": ["Jarabes de Miel","Jarabes naturales"], "descuentos": {"20": 48.00, "25": 45.00, "30": 42.00, "40": 36.00}},
  {"id": 40, "categoria": "Línea Convencional", "producto": "Miel de abejas, sábila, kion, propóleos, muña y camu camu x 200ml", "puntos": 8.33, "pvp": 40.00, "precio_original": 50.00, "etiqueta_descuento": "-20%", "imagen": "img/miel-de-abejas-sabila-1-800x800.jpg", "descripcion": "Jarabe natural que combina miel de abejas, sábila, kion, propóleos, muña y camu camu.", "categorias": ["Jarabes de Miel","Jarabes naturales","Para los Pulmones"], "descuentos": {"20": 40.00, "25": 37.50, "30": 35.00, "40": 30.00}},
  {"id": 41, "categoria": "Línea Convencional", "producto": "Propóleos en solución x 30 ml", "puntos": 13.33, "pvp": 80.00, "imagen": "img/propoleos-en-solucion-santa-natura-800x800.jpg", "descripcion": "Los propóleos son mezclas de las resinas de la yema y la corteza de los árboles, recolectadas por las abejas. Presentación en solución de 30 ml.", "categorias": ["Para los Pulmones","Propóleos"], "descuentos": {"20": 64.00, "25": 60.00, "30": 56.00, "40": 48.00}},
  {"id": 42, "categoria": "Línea Convencional", "producto": "Propóleos en spray x 30 ml", "puntos": 8.33, "pvp": 50.00, "imagen": "img/miel_aromatica-300x300.jpg", "descripcion": "Los propóleos son mezclas de las resinas de la yema y la corteza de los árboles, recolectadas por las abejas. Presentación en spray de 30 ml.", "categorias": ["Para los Pulmones","Propóleos"], "descuentos": {"20": 40.00, "25": 37.50, "30": 35.00, "40": 30.00}},
  {"id": 43, "categoria": "Línea Convencional", "producto": "Vinagre de manzana x 500 ml", "puntos": 5.33, "pvp": 32.00, "imagen": "img/vinagre_sidra_sinfondo-300x300.jpg", "categorias": ["Cocina Natural","Detox","Para el Estomágo","Para las Vías Urinarias","Vinagres"], "descuentos": {"20": 25.60, "25": 24.00, "30": 22.40, "40": 19.20}},
  {"id": 44, "categoria": "Línea Convencional", "producto": "Frota-T x 90 g", "puntos": 8.33, "pvp": 50.00, "imagen": "img/unguento-frota-t-santa-natura-300x300.jpg", "descripcion": "Frota-T alivia el dolor muscular y articular de forma natural. Presentación de 90 g.", "categorias": ["Frotaciones","Para los Huesos"], "descuentos": {"20": 40.00, "25": 37.50, "30": 35.00, "40": 30.00}},
  {"id": 45, "categoria": "Línea Convencional", "producto": "Aceite esencial de Eucalipto Gotero x 10ml", "puntos": 11.67, "pvp": 70.00, "categorias": ["Aceites"], "descuentos": {"20": 56.00, "25": 52.50, "30": 49.00, "40": 42.00}},
  {"id": 46, "categoria": "Línea Convencional", "producto": "Aceite esencial de Eucalipto Roll On x 10ml", "puntos": 11.67, "pvp": 70.00, "categorias": ["Aceites"], "descuentos": {"20": 56.00, "25": 52.50, "30": 49.00, "40": 42.00}},
  {"id": 47, "categoria": "Línea Convencional", "producto": "Aceite esencial de Palo Santo Gotero x 10ml", "puntos": 15.00, "pvp": 90.00, "categorias": ["Aceites"], "descuentos": {"20": 72.00, "25": 67.50, "30": 63.00, "40": 54.00}},
  {"id": 48, "categoria": "Línea Convencional", "producto": "Aceite esencial de Palo Santo Roll On x 10ml", "puntos": 15.00, "pvp": 90.00, "categorias": ["Aceites"], "descuentos": {"20": 72.00, "25": 67.50, "30": 63.00, "40": 54.00}},
  {"id": 49, "categoria": "Línea Convencional", "producto": "Aceite esencial de Orégano Gotero x 10ml", "puntos": 11.67, "pvp": 70.00, "categorias": ["Aceites"], "descuentos": {"20": 56.00, "25": 52.50, "30": 49.00, "40": 42.00}},
  {"id": 50, "categoria": "Línea Convencional", "producto": "Shampoo de Quina x 290ml", "puntos": 16.50, "pvp": 99.00, "imagen": "img/shampoo-quinua-300x300.jpg", "descripcion": "Shampoo de Quina: cuida y fortalece tu cabello desde la raíz. Presentación de 290 ml.", "categorias": ["Cuidado del cabello","Favoritos de las mujeres","Top Ventas"], "descuentos": {"20": 79.20, "25": 74.25, "30": 69.30, "40": 59.40}},
  {"id": 51, "categoria": "Línea Consumo Saludable", "producto": "Aceite de coco x 230 ml", "puntos": 2.33, "pvp": 35.00, "imagen": "img/aceite-de-coco-2-300x300.jpg", "categorias": ["Aceites","Cocina Natural","Para las Defensas"], "descuentos": {"15": 29.75}},
  {"id": 52, "categoria": "Línea Consumo Saludable", "producto": "Aceite de oliva extra virgen x 500 ml", "puntos": 3.47, "pvp": 52.00, "imagen": "img/aceite-oliva-300x300.jpg", "categorias": ["Aceites","Cocina Natural","Refuerzos"], "descuentos": {"15": 44.20}},
  {"id": 53, "categoria": "Línea Consumo Saludable", "producto": "Aceite sacha inchi extra virgen x 250 ml", "puntos": 3.47, "pvp": 52.00, "imagen": "img/aceite-sacha-inti-300x300.jpg", "categorias": ["Aceites","Cocina Natural","Para el Sistema Nervioso","Para las Defensas"], "descuentos": {"15": 44.20}},
  {"id": 54, "categoria": "Línea Consumo Saludable", "producto": "Miel de abejas x 370 g", "puntos": 2.67, "pvp": 40.00, "imagen": "img/miel-de-abejas-3-300x300.jpg", "descripcion": "Superalimento producido por las abejas a partir del néctar de las flores. Presentación de 370 g.", "categorias": ["Cocina Natural","Miel","Para los Pulmones","Top Ventas"], "descuentos": {"15": 34.00}},
  {"id": 55, "categoria": "Línea Consumo Saludable", "producto": "Sal Rosada Premium x 500 g", "puntos": 1.20, "pvp": 18.00, "imagen": "img/Sal-rosada-2-300x300.jpg", "descripcion": "Sal extraída de las alturas de los Andes peruanos, directamente y sin refinar. Presentación de 500 g.", "categorias": ["Cocina Natural"], "descuentos": {"15": 15.30}},
  {"id": 56, "categoria": "Packs", "producto": "PACK LIVIANO POR DENTRO", "pvp": 126.00, "precio_original": 180.00, "etiqueta_descuento": "-30%", "imagen": "img/pack-liviano.png", "descripcion": "Contiene: 1 Concentrado de Alcachofa 500 ml, 1 Bebida Concentrada de Chancapiedra 500 ml, 1 Concentrado de Té Verde 200 ml. Tres concentrados en sinergia para depurar hígado, riñones y vesícula.", "puntos": 21.00, "categorias": ["Detox","Packs","Peso / Grasa","Top Ventas"], "descuentos": {"15": 113.40}},
  {"id": 57, "categoria": "Packs", "producto": "PACK ARTICULACIONES PRO MARACUYA", "pvp": 275.80, "precio_original": 394.00, "etiqueta_descuento": "-30%", "imagen": "img/pack-articulaciones-pro-maracuya-300x300.png", "descripcion": "Contiene: 1 Colágeno Hidrolizado de Maracuyá 450 gr, 1 Carti Mix 200 gr, 1 Vitamagne. Cuidado de articulaciones, cartílagos, huesos y músculos.", "puntos": 45.97, "categorias": ["Colágenos","Favoritos de las mujeres","Favoritos de los hombres","Packs","Packs Colágeno","Packs Cyber","Para los Huesos","Top Ventas"], "descuentos": {"15": 248.22}},
  {"id": 58, "categoria": "Packs", "producto": "PACK ARTICULACIONES PRO PLUS", "pvp": 275.80, "precio_original": 394.00, "etiqueta_descuento": "-30%", "imagen": "img/pack-articulaciones-pro-plus-300x300.png", "descripcion": "Contiene: 1 Colágeno Hidrolizado Plus 450 gr, 1 Carti Mix, 1 Vitamagne. Cuidado integral de articulaciones, huesos y músculos.", "puntos": 45.97, "categorias": ["Colágenos","Favoritos de las mujeres","Favoritos de los hombres","Packs","Packs Colágeno","Packs Cyber","Para los Huesos","Top Ventas"], "descuentos": {"15": 248.22}},
  {"id": 59, "categoria": "Packs", "producto": "PACK ARTICULACIONES PRO PREMIUM", "pvp": 275.80, "precio_original": 394.00, "etiqueta_descuento": "-30%", "imagen": "img/pack-articulaciones-pro-premium-300x300.png", "descripcion": "Contiene: 1 Colágeno Hidrolizado Premium 450 gr, 1 Carti Mix, 1 Vitamagne.", "puntos": 45.97, "categorias": ["Colágenos","Favoritos de las mujeres","Favoritos de los hombres","Packs","Packs Colágeno","Packs Cyber","Para los Huesos","Top Ventas"], "descuentos": {"15": 248.22}},
  {"id": 60, "categoria": "Packs", "producto": "PACK X2 TÉ VERDE 200 ML", "pvp": 56.00, "precio_original": 70.00, "etiqueta_descuento": "-20%", "imagen": "img/productossn-300x300.jpg", "descripcion": "Contiene: 2 Concentrados de Té Verde de 200 ml. Formato ahorro; se toma puro o diluido en agua fría o caliente.", "puntos": 9.33, "categorias": ["Detox","Packs","Packs Cyber","Peso / Grasa"], "descuentos": {"15": 50.40}},
  {"id": 61, "categoria": "Packs", "producto": "PACK 2 SUPERTRIM + 2 TE VERDE + 1 GEL REDUCTOR DE REGALO", "pvp": 214.40, "precio_original": 268.00, "etiqueta_descuento": "-20%", "imagen": "img/packsupertim-gel-300x300.jpg", "descripcion": "Contiene: 2 Supertrim, 2 Concentrados de Té Verde 200 ml y 1 Gel Reductor de regalo.", "puntos": 35.73, "categorias": ["Detox","Packs","Packs Cyber","Top Ventas"], "descuentos": {"15": 192.96}},
  {"id": 62, "categoria": "Packs", "producto": "PACK DETOX", "pvp": 217.50, "precio_original": 290.00, "etiqueta_descuento": "-25%", "imagen": "img/packdetox_f-300x300.jpg", "descripcion": "Contiene: 1 Supertrim 75 g, 1 Toxizero 75 g, 1 Concentrado de Alcachofa 500 ml, 1 Concentrado de Té Verde 200 ml.", "puntos": 36.25, "categorias": ["Detox","Packs","Packs Cyber","Para el Estomágo","Peso / Grasa"], "descuentos": {"15": 195.75}},
  {"id": 63, "categoria": "Packs", "producto": "PACK DESINTÓXICATE", "pvp": 141.00, "precio_original": 188.00, "etiqueta_descuento": "-25%", "imagen": "img/pack-desintoxicate-sn-300x300.jpg", "descripcion": "Contiene: 1 Toxizero 75 g, 1 Concentrado de Alcachofa 500 ml, 1 Vinagre de Sidra de Manzana 500 ml.", "puntos": 23.50, "categorias": ["Detox","Packs","Packs Cyber","Para el Estomágo","Peso / Grasa"], "descuentos": {"15": 126.90}},
  {"id": 64, "categoria": "Packs", "producto": "PACK HUESOS SANOS", "pvp": 428.00, "precio_original": 608.00, "etiqueta_descuento": "-30%", "imagen": "img/PACK-HUESOS-SANOS-300x300.jpg", "descripcion": "Cuida tu estructura ósea de forma completa con esta poderosa combinación natural.", "puntos": 71.33, "categorias": ["Packs","Packs Colágeno","Para los Huesos","Top Ventas"], "descuentos": {"15": 385.20}},
  {"id": 65, "categoria": "Packs", "producto": "PACK DIGESTIVO", "pvp": 218.40, "precio_original": 312.00, "etiqueta_descuento": "-30%", "imagen": "img/pack-digestivo-web-2-800x800.jpg", "descripcion": "Cuida tu sistema digestivo de manera natural con la combinación de dos superalimentos.", "puntos": 36.40, "categorias": ["Favoritos de la semana","Packs","Packs Cyber","Para el Estomágo","Peso / Grasa"], "descuentos": {"15": 196.56}},
  {"id": 66, "categoria": "Packs", "producto": "PACK MIX PLUS PREMIUM", "pvp": 410.00, "precio_original": 590.00, "etiqueta_descuento": "-31%", "imagen": "img/pack-mix-plus-premium-800x800.jpg", "descripcion": "El dúo de colágenos que tus huesos necesitan, en versión Plus y Premium.", "puntos": 68.33, "categorias": ["Packs","Packs Colágeno","Para los Huesos"], "descuentos": {"15": 369.00}},
  {"id": 67, "categoria": "Packs", "producto": "PACK KALMAPROSS INTEGRAL", "pvp": 358.00, "precio_original": 426.00, "etiqueta_descuento": "-16%", "imagen": "img/pack-integral-kalmapross-800x800.jpg", "descripcion": "Contiene Kalmapross, nuestro concentrado desinflamante natural para la próstata, junto al Concentrado de Chancapiedra.", "puntos": 59.67, "categorias": ["Favoritos de los hombres","Packs","Packs Hombre","Para las Vías Urinarias"], "descuentos": {"15": 322.20}},
  {"id": 68, "categoria": "Packs", "producto": "PACK GASTRO", "pvp": 380.00, "precio_original": 516.00, "etiqueta_descuento": "-26%", "imagen": "img/pack-gastro-300x300.jpg", "descripcion": "Los superalimentos que tu estómago necesita. Contiene 3 Concentrados de Aloe y complementos.", "puntos": 63.33, "categorias": ["Packs","Packs Cyber","Para el Estomágo","Peso / Grasa"], "descuentos": {"15": 342.00}},
  {"id": 69, "categoria": "Packs", "producto": "PACK HIGADO SANO", "pvp": 229.00, "precio_original": 297.00, "etiqueta_descuento": "-23%", "imagen": "img/pack-higado-sano-300x300.jpg", "descripcion": "Contiene los productos ideales para favorecer la función hepática.", "puntos": 38.17, "categorias": ["Detox","Packs","Para el Estomágo","Peso / Grasa","Top Ventas"], "descuentos": {"15": 206.10}},
  {"id": 70, "categoria": "Packs", "producto": "PACK ARTICULACIONES PREMIUM", "pvp": 279.00, "precio_original": 329.00, "etiqueta_descuento": "-15%", "imagen": "img/pack-articulaciones-premium-300x300.jpg", "descripcion": "Contiene: 1 Colágeno Hidrolizado Premium 450 gr, 1 Vitamagne, 1 FROTA-T.", "puntos": 46.50, "categorias": ["Packs","Packs Colágeno","Para los Huesos"], "descuentos": {"15": 251.10}},
  {"id": 71, "categoria": "Packs", "producto": "PACK HOMBRE VIRILIDAD", "pvp": 249.60, "precio_original": 312.00, "etiqueta_descuento": "-20%", "imagen": "img/pack-hombre-virilidad-300x300.jpg", "descripcion": "Los dos superalimentos esenciales para el hombre, con Kalmapross como desinflamante natural para la próstata.", "puntos": 41.60, "categorias": ["Favoritos de los hombres","Packs","Packs Hombre","Para las Vías Urinarias"], "descuentos": {"15": 224.64}},
  {"id": 72, "categoria": "Packs", "producto": "PACK BÁSICO KALMAPROSS", "pvp": 292.00, "precio_original": 360.00, "etiqueta_descuento": "-19%", "imagen": "img/pack-basico-kalmapross-300x300.jpg", "descripcion": "Lo ideal para favorecer la salud de los hombres, en su versión básica.", "puntos": 48.67, "categorias": ["Favoritos de los hombres","Packs","Packs Hombre","Para las Vías Urinarias","Top Ventas"], "descuentos": {"15": 262.80}},
  {"id": 73, "categoria": "Packs", "producto": "PACK 2 COLÁGENOS PREMIUM + 2 COLÁGENOS PLUS", "pvp": 540.00, "precio_original": 720.00, "etiqueta_descuento": "-25%", "imagen": "img/9-300x300.jpg", "descripcion": "Contiene: 2 Colágenos Hidrolizados Premium 450 gr, 2 Colágenos Hidrolizados Plus 450 gr.", "puntos": 90.00, "categorias": ["Packs","Packs Colágeno","Para los Huesos"], "descuentos": {"15": 486.00}},
  {"id": 74, "categoria": "Packs", "producto": "PACK ARTICULACIONES MARACUYA", "pvp": 279.00, "precio_original": 329.00, "etiqueta_descuento": "-15%", "imagen": "img/pack-articulaciones-maracuya-300x300.jpg", "descripcion": "Contiene: 1 Colágeno Hidrolizado de Maracuyá 450 gr, 1 Vitamagne, 1 Frota-T.", "puntos": 46.50, "categorias": ["Colágenos","Packs","Packs Colágeno","Para los Huesos"], "descuentos": {"15": 251.10}},
  {"id": 75, "categoria": "Packs", "producto": "PACK 2 HOMBRE VIRILIDAD", "pvp": 452.00, "precio_original": 540.00, "etiqueta_descuento": "-16%", "imagen": "img/pack-virilidad-hombre-2-300x300.jpg", "descripcion": "Contiene: 2 Harinas de Maca Gelatinizada, 2 Kalmapross 500 ml, 3 Batidos Yo Vital Hombre.", "puntos": 75.33, "categorias": ["Packs","Packs Hombre"], "descuentos": {"15": 406.80}},
  {"id": 76, "categoria": "Packs", "producto": "PACK HUESOS Y DEFENSAS HOMBRE", "pvp": 516.00, "precio_original": 584.00, "etiqueta_descuento": "-12%", "imagen": "img/pack-huesos-y-defensas-hombre-300x300.jpg", "descripcion": "Contiene: 2 Colágenos Hidrolizados Premium 450 gr, 2 Kalmapross 500 ml, 1 Batido Yo Vital Hombre.", "puntos": 86.00, "categorias": ["Colágenos","Packs","Packs Colágeno","Packs Hombre","Para los Huesos"], "descuentos": {"15": 464.40}},
  {"id": 77, "categoria": "Packs", "producto": "PACK VITALIDAD HOMBRE", "pvp": 584.00, "precio_original": 672.00, "etiqueta_descuento": "-13%", "imagen": "img/pack-vitalidad-hombre-800x800.jpg", "descripcion": "Contiene: 2 Colágenos Hidrolizados Premium 450 gr, 2 Kalmapross 500 ml, 2 Batidos Yo Vital Hombre.", "puntos": 97.33, "categorias": ["Packs","Packs Hombre"], "descuentos": {"15": 525.60}},
  {"id": 78, "categoria": "Packs", "producto": "PACK ARTICULACIONES PLUS", "pvp": 279.00, "precio_original": 329.00, "etiqueta_descuento": "-15%", "imagen": "img/pack-articulaciones-plus-800x800.jpg", "descripcion": "Contiene: 1 Colágeno Hidrolizado Plus, 1 Vitamagne, 1 FROTA-T.", "puntos": 46.50, "categorias": ["Colágenos","Packs","Packs Colágeno","Para los Huesos"], "descuentos": {"15": 251.10}},
  {"id": 79, "categoria": "Packs", "producto": "PACK GLUCONTROL + HOJAS DE OLIVO+ MORINGA", "pvp": 360.00, "precio_original": 428.00, "etiqueta_descuento": "-16%", "imagen": "img/pack-glucontrol1-800x800.jpg", "descripcion": "Nuestro Glucontrol es el aliado que necesitas para acompañar el control de tus niveles de glucosa, junto a Hojas de Olivo y Moringa.", "puntos": 60.00, "categorias": ["Packs","Para el Estomágo","Para las Defensas"], "descuentos": {"15": 324.00}},
  {"id": 80, "categoria": "Packs", "producto": "PACK X2 COLÁGENO HIDROLIZADO PREMIUM", "pvp": 270.00, "precio_original": 360.00, "etiqueta_descuento": "-25%", "imagen": "img/productossn-5-300x300.jpg", "descripcion": "2 Colágenos Hidrolizados Premium con Camu Camu. Composición: colágeno hidrolizado y camu camu.", "puntos": 45.00, "categorias": ["Colágenos","Packs","Packs Colágeno","Para los Huesos"], "descuentos": {"15": 243.00}},
  {"id": 81, "categoria": "Packs", "producto": "PACK X2 COLÁGENO HIDROLIZADO PLUS", "pvp": 270.00, "precio_original": 360.00, "etiqueta_descuento": "-25%", "imagen": "img/productossn-4-300x300.jpg", "descripcion": "2 Colágenos Hidrolizados Plus. Composición: colágeno hidrolizado, maíz morado, fresa y camu camu.", "puntos": 45.00, "categorias": ["Colágenos","Packs","Packs Colágeno","Para los Huesos"], "descuentos": {"15": 243.00}},
  {"id": 82, "categoria": "Packs", "producto": "PACK X2 COLÁGENO MARACUYÁ Y CAMU CAMU", "pvp": 270.00, "precio_original": 360.00, "etiqueta_descuento": "-25%", "imagen": "img/productossn-6-300x300.jpg", "descripcion": "2 Colágenos Hidrolizados con Maracuyá y Camu Camu, alimentos ricos en vitamina C.", "puntos": 45.00, "categorias": ["Colágenos","Packs","Packs Colágeno","Para los Huesos"], "descuentos": {"15": 243.00}},
  {"id": 83, "categoria": "Packs", "producto": "PACK DEPORTIVO", "pvp": 410.00, "precio_original": 590.00, "etiqueta_descuento": "-31%", "imagen": "img/Pack-Deportivo-300x300.jpg", "descripcion": "Ideal para quienes realizan rutinas de entrenamiento y desean cuidar sus articulaciones.", "puntos": 68.33, "categorias": ["Colágenos","Favoritos de los hombres","Packs","Packs Colágeno","Para las Defensas","Para los Huesos"], "descuentos": {"15": 369.00}},
  {"id": 84, "categoria": "Packs", "producto": "PACK ARTICULACIONES", "pvp": 410.00, "precio_original": 590.00, "etiqueta_descuento": "-31%", "imagen": "img/Pack-Articulaciones-300x300.jpg", "descripcion": "Ideal para quienes desean cuidar sus articulaciones o padecen alguna molestia articular.", "puntos": 68.33, "categorias": ["Colágenos","Packs","Packs Colágeno","Para las Defensas","Para los Huesos"], "descuentos": {"15": 369.00}},
  {"id": 85, "categoria": "Packs", "producto": "PACK JUVENTUD QUE SE SIENTE", "pvp": 410.00, "precio_original": 590.00, "etiqueta_descuento": "-31%", "imagen": "img/Pack_belleza-300x300.jpg", "descripcion": "Ideal para quienes desean cuidar su piel y sus articulaciones. Enfocado principalmente en colágeno y Carti Mix.", "puntos": 68.33, "categorias": ["Colágenos","Packs","Packs Colágeno","Para las Defensas","Para los Huesos"], "descuentos": {"15": 369.00}}
];

/* ----------------------------------------------------------------------------
   Categorías de santanatura.com.pe — las que manda el menú de la tienda.
   ----------------------------------------------------------------------------
   El orden de esta lista es el orden en que salen en el menú y en la barra
   lateral, así que reordénala si quieres destacar otra categoría primero.

   Las `hijas` son subcategorías reales del sitio. Al filtrar por una madre se
   incluyen también los productos de sus hijas, porque no todos los productos
   llevan las dos etiquetas (p. ej. el Pack x2 Té Verde está en «Detox» pero no
   en «Top Ventas»).

   Los nombres deben coincidir EXACTOS con los del campo `categorias` de cada
   producto. Ojo con «Para el Estomágo»: la tienda lo escribe así, con la tilde
   en la letra equivocada, y aquí se respeta para que todo calce.
   -------------------------------------------------------------------------- */
const COLECCIONES = [
    { nombre: 'Top Ventas',             hijas: ['Descanso y relax', 'Detox', 'Favoritos de las mujeres', 'Favoritos de los hombres'] },
    { nombre: 'Packs',                  hijas: ['Packs Colágeno', 'Packs Cyber', 'Packs Hombre'] },
    { nombre: 'Colágenos',              hijas: [] },
    { nombre: 'Refuerzos',              hijas: ['Batidos', 'Harinas del mar y tierra'] },
    { nombre: 'Bebidas y concentrados', hijas: ['Bebidas', 'Concentrados'] },
    { nombre: 'Para las Defensas',      hijas: [] },
    { nombre: 'Para los Huesos',        hijas: [] },
    { nombre: 'Para el Estomágo',       hijas: [] },
    { nombre: 'Para las Vías Urinarias', hijas: [] },
    { nombre: 'Para los Pulmones',      hijas: [] },
    { nombre: 'Para el Sistema Nervioso', hijas: [] },
    { nombre: 'Peso / Grasa',           hijas: [] },
    { nombre: 'Jarabes naturales',      hijas: ['Jarabes de Miel'] },
    { nombre: 'Propóleos',              hijas: [] },
    { nombre: 'Aceites',                hijas: [] },
    { nombre: 'Cocina Natural',         hijas: ['Algarrobina', 'Miel', 'Vinagres'] },
    { nombre: 'Frotaciones',            hijas: [] },
    { nombre: 'Cuidado del cabello',    hijas: [] },
    { nombre: 'Favoritos de la semana', hijas: [] }
];

/* Líneas de la lista oficial de precios. Ya no se muestran en el menú, pero se
   conservan en el campo `categoria` de cada producto porque de ellas depende
   qué escala de descuentos por cantidad aplica. */
const CATEGORIAS = ["Línea General", "Línea Convencional", "Línea Consumo Saludable", "Packs"];
